### Use Rest Client VSCode Extension - https://github.com/Huachao/vscode-restclient


###

GET http://localhost:9000/api/v1/url


###

POST http://localhost:9000/api/v1/shorten
Content-Type: application/json

{
    "url": "GET http://localhost:9000/api/v1/6074f0"
}


###

GET http://localhost:9000/api/v1/6074f0